//No AI was used to write this program, I have alergy to ai slop. The only thing ai generated is
//the translation of pHash algorithm (which was ai generated by the author anyway)
//Also, i learned rust like 1 year ago, so this probably can be optimised
//
//28.05.2026 Added parsing data/video_data.txt into struct
//29.05.2026 Added parsing data/watch_page_data.txt, data/asset_data.txt, data/history_data.txt
//   into vectors, added searching through firefox's browsing history, added filetype checker,
//   added primitive browser cache scanner
//30.05.2026 Path are now proper PathBuf type not &str. Added FFmpeg extractor of frames from
//   videos. Added pHash generator from images. Added primitive comparator of hashes.
//31.05.2026 Replaced the good, well functioning pHash generator with ai generated translation of
//   pHash.cpp because they gave different results, improved frame extractor to use image2 instead of rawvideo,
//   improved comparator of hashes
//01.06.2026 Made "hash" of VideoData structure a vector.
//   Hashing works well, and fast

// TODO Generation of hashes and comparation should be
	// in separate functions NOT in browser_cache_scan...
// TODO Make "0000000000000000" hash be a None.
// TODO Turn the hash comparsing function upside down:
	// iterate over every entry in video_data.txt against every cache entry,
	// not the other way around.
// TODO Do something about the ffmpeg bottlneck maybe...

mod phash_ai_slop;

use dirs::home_dir;
use ffmpeg_sidecar::command::FfmpegCommand;
use rusqlite::{params, Connection, ErrorCode};
use rusqlite::ErrorCode::DatabaseBusy;
use std::fs::read_to_string;
use std::path::{Path, PathBuf};
use std::sync::LazyLock;
use std::error::Error;
use std::{env, fs};
use ini::Ini;

//Constants and statics, mainly paths. LazyLock is a saviour <3
//MOVE ALL THOSE TO MATCH FUNCTIONS

static BASE_DIR: LazyLock<PathBuf> = LazyLock::new(|| {
    let path = PathBuf::from("./");
    if !path.is_dir() {
        panic!("Cannot read base dir!: {}", path.display());
    }

    path
});

static DATA_DIR: LazyLock<PathBuf> = LazyLock::new(|| {
    let path = BASE_DIR.join("data");
    if !path.is_dir() {
        panic!("Cannot read data dir!: {}", path.display());
    }

    path
});

//NO BROWSER PROFILES AS LAZYLOCK, I CHANGED MY MIND IT'S A MESS

static LIBREWOLF_CACHE_DIR: LazyLock<PathBuf> = LazyLock::new(|| {
    home_dir()
        .expect("Cannot read $HOME")
        .join(".cache")
        .join("librewolf")
});

//Struct for parsing video_data.txt
//"Roblox+Video+101|-8128339497863628282,39c9cb3870db6751|0000000000000000|00:03:52.43|00:03:52.63"
//VIDEO TITLE|GOOGLE_VIDEO_ID,GOOGLE_VIDEO_CONTENT_ID|HASH|DUR_MIN|DUR_MAX
struct VideoData {
    //IN video_data.txt THIS IS A REGEX SPERATED BY + (i think)
    title: String,
    ids: Vec<String>,
    hash: Vec<u64>,
    duration_min: String,
    duration_max: String,
}

struct DataSet {
    video_data: Vec<VideoData>,
    watch_page_data: Vec<String>,
    asset_data: Vec<String>,
    history_data: Vec<String>,
}

fn read_lines(path: impl AsRef<Path>) -> Vec<String> {
    read_to_string(path.as_ref())
        .expect("Error reading file")
        .lines()
        .map(String::from)
        .collect()
}

fn load_dataset() -> DataSet {
    //Loading dataset
    //Read lines of video_data.txt
    let video_data_path = DATA_DIR.join("video_data.txt");
    let video_data = read_lines(&video_data_path);

    let mut video_data_struct_vec: Vec<VideoData> = Vec::new();

    //process each line of the file
    for entry in video_data {
        //remove quotes from the line
        let entry_sanitised = &entry
            .strip_prefix('"')
            .and_then(|entry| entry.strip_suffix('"'))
            .unwrap_or(&entry);
        //split the line by "|" into a vector
        let entry_vec: Vec<&str> = entry_sanitised.split("|").collect();
        if entry_vec.len() != 5 {
            panic!("Some entry has less than 5 elements!"); // panic when not enough data!!!
        };

        //create VideoData structure from vector
        let entry_struct = VideoData {
            title: entry_vec[0].to_string(),
            ids: entry_vec[1]
                .split(",") //split ids by ","
                .map(|p| p.to_string())
                .collect(),
            hash: entry_vec[2]
				.split(",")
				.filter_map(|h| u64::from_str_radix(h, 16).ok())
				.collect(),
            duration_min: entry_vec[3].to_string(),
            duration_max: entry_vec[4].to_string(),
        };

        video_data_struct_vec.push(entry_struct);
    }
    println!(
        "Loaded {} entries from {}",
        video_data_struct_vec.len(),
        video_data_path.display()
    );
    let watch_page_data_path = DATA_DIR.join("watch_page_data.txt");
    let watch_page_data = read_lines(&watch_page_data_path);
    println!(
        "Loaded {} entries from {}",
        watch_page_data.len(),
        watch_page_data_path.display()
    );
    let asset_data_path = DATA_DIR.join("asset_data.txt");
    let asset_data = read_lines(&asset_data_path);
    println!(
        "Loaded {} entries from {}",
        asset_data.len(),
        asset_data_path.display()
    );
    let history_data_path = DATA_DIR.join("history_data.txt");
    let history_data = read_lines(&history_data_path);
    println!(
        "Loaded {} entries from {}",
        history_data.len(),
        history_data_path.display()
    );

    DataSet {
        video_data: video_data_struct_vec,
        watch_page_data: watch_page_data,
        asset_data: asset_data,
        history_data: history_data,
    }
}

fn get_browser_history_profile_root(browser_name: &str) -> Option<PathBuf> {
	match browser_name {
		"firefox" => Some(home_dir().expect("Cannot read $HOME").join(".mozilla/firefox")),
		"librewolf" => Some(home_dir().expect("Cannot read $HOME").join(".config/librewolf/librewolf")),
		"chrome" => Some(home_dir().expect("Cannot read $HOME").join(".config/google-chrome")),
		_ => panic!("Browser not covered")
	}
}

fn get_profile_list(browser_name: &str) -> Vec<String> {
	let profile_list_file = match browser_name {
		"firefox" | "librewolf" => "profiles.ini",
		//"chrome" => "SHIT",
		_ => panic!("Browser not covered")
	};
	let browser_history_profile_root = get_browser_history_profile_root(&browser_name);
	let profile_list_file_path = browser_history_profile_root
		.expect("WOOF")
		.join(profile_list_file);
	
	let profiles_list_file_content = Ini::load_from_file(&profile_list_file_path).unwrap();
	
	let mut profile_list_vector: Vec<String> = Vec::new();
	
	for (section, props) in profiles_list_file_content.iter() {
		if let Some(section_name) = section {
			if section_name.starts_with("Profile") {
				match props.get("Path") {
					Some(path) => profile_list_vector.push(path.to_owned()),
					None => panic!("Profile section is missing Path value, skipping..."),
				}
			}
		}
	}
	
	profile_list_vector
}

fn get_profile_history(browser_name: &str) -> &str {
	match browser_name {
		"firefox" | "librewolf" => "places.sqlite",
		"chrome" => "History",
		_ => panic!("Browser not covered")
	}
}

fn browser_history_scan(browser_name: &str, search_vector: Vec<String>) {
    println!("Scanning browser history...");
    
    let browser_history_profile_root = get_browser_history_profile_root(&browser_name)
										.expect("FRICK");
	let profile_history = get_profile_history(&browser_name);
    
    //get history file of a profile
    let profile_list_vector = get_profile_list("librewolf");
	println!("{:#?}", profile_list_vector);
    
    for folder in profile_list_vector {
		let folder = PathBuf::from(folder);
		//firefox and its forks uses places.sqlite, chrome uses History which is (sqlite3)
		let history_file = browser_history_profile_root
			.join(folder.as_path()).join(get_profile_history(&browser_name));
		if history_file.is_file() {
			println!("{:#?}", history_file.display());
			let conn = match browser_name {
				"firefox" | "librewolf" =>
					Connection::open(history_file).expect("Cannot open places.sqlite"),
				//"chrome" =>
					//Connection::open("History").expect("Cannot open History"),
				_ => panic!("Browser not covered: {}", browser_name)
			};
			let query = match browser_name {
				"firefox" | "librewolf" => "SELECT url, title FROM moz_places WHERE url LIKE ?1",
				// "chrome" => "SELECT ??? FROM ??? WHERE ??? LIKE ?1",
				_ => panic!("Browser not covered: {}", browser_name)
			};
			
			let mut stmt = match conn.prepare(query) {
				Ok(response) => response,
				Err(error) => {
					if let rusqlite::Error::SqliteFailure(err, _) = error {
						match err.code {
							rusqlite::ErrorCode::DatabaseBusy => {
								panic!("The browser history database is locked, perhaps the browser is still running? Close it first.");
							}
							_ => panic!("Failed to prepare query due to an error: {:#?}", error),
						}
					} else {
						panic!("Failed to prepare query due to an error: {:#?}", error);
					}
				}
			};
			
			for search in &search_vector {
				//build search querry
				let pattern = format!("%{}%", search);
	
				//prepare query that will search for stuff and execute it
				let mut rows = stmt.query(params![pattern]).expect("Query failed");
	
				// loop through rows
				while let Some(row) = rows.next().expect("Failed to fetch row") {
					let url: Option<String> = row.get(0).unwrap_or_default();
					let title: Option<String> = row.get(1).unwrap_or_default();
					println!(
						"url: {}, title: {}",
						url.unwrap_or_default(),
						title.unwrap_or_default()
					);
				}
			}
		} else {
			println!("{} does not exists", history_file.display())
		}
	}
}

// check file mime type
fn check_filetype(path: impl AsRef<Path>) -> Option<String> {
    let kind = infer::get_from_path(path).ok()??;
    Some(kind.mime_type().to_string())
}

fn get_browser_cache_profile_root(browser_name: &str) -> Option<PathBuf> {
    let home = dirs::home_dir()?;

    match browser_name {
        "firefox" => Some(home.join(".cache/firefox")),
        "librewolf" => Some(home.join(".cache/librewolf")),
        "chrome" => Some(home.join(".config/google-chrome")),
		_ => panic!("No such browser")
    }
}

fn get_profile_cache(browser: &str) -> Option<&str> {

    match browser {
        "firefox" | "librewolf" => Some("cache2/entries"),
        "chrome" => None,
        _ => None,
    }
}

fn browser_cache_scan(browser_name: &str, video_data: &Vec<VideoData>) {
    println!("Scanning {}'s cache...", browser_name);
	
	let browser_cache_profile_root = get_browser_cache_profile_root(browser_name).expect("DAMN");
    let profile_cache = get_profile_cache(browser_name).expect("CRAP");
    
    println!("Browser profile root is {}", browser_cache_profile_root.display());
   
    for folder in fs::read_dir(&browser_cache_profile_root).expect("No profiles?") {
        let folder_cache_path = &browser_cache_profile_root.join(folder.expect("POOP").path())
								.join(&profile_cache);
        
        if folder_cache_path.is_dir() {
            println!("Scanning {:?}", folder_cache_path);
            if let Ok(cache_entries) = fs::read_dir(&folder_cache_path) {
                for cache_entry in cache_entries {
                    let cache_entry_path = cache_entry.unwrap().path();
                    //is it a file and a video file
                    if cache_entry_path.is_file() {
                        //initialize vector of similarity values
                        let mut similarity = Vec::new();
                        
                        let buf = fs::read(&cache_entry_path).unwrap();
                        if infer::is_video(&buf) {//|| infer::is_image(&buf){
							//println!("{:?}", cache_entry_path);
                            //extract frame and gen hash
                            let cache_entry_file_name = &cache_entry_path
                                .file_name()
                                .unwrap()
                                .to_string_lossy()
                                .into_owned();

                            //if the temporary dir is there remove it
                            //if not, create it, use it and then remove it
                            let potential_file_path = env::temp_dir().join(cache_entry_file_name);
                            if potential_file_path.is_dir() {
                                fs::remove_dir_all(&potential_file_path).unwrap();
                            }
                            fs::create_dir(&potential_file_path).unwrap();
                            let tmp_file = env::temp_dir()
                                .join(&cache_entry_file_name)
                                .join("frame_%03d.raw");

                            extract_videoframes(
                                PathBuf::from(&cache_entry_path),
                                PathBuf::from(&tmp_file),
                            );
							
							//check every raw frame of a cached video
							//against every hash in video_data.txt
                            for file in fs::read_dir(&potential_file_path).unwrap() {
                                // search dir for all raw files
                                let path = file.unwrap().path();
                                let filepath = path.to_str().unwrap();
								
                                let hash_to_check = phash_ai_slop::generate_phash(filepath);
								
								for video_data_entry in video_data {
									println!("{:?}", video_data_entry.title);
									//put the list of frames similarity into a vector,
									//and then find the smallest number in that vector
									for &video_data_entry_hash in &video_data_entry.hash {
										let result = hamming(video_data_entry_hash, hash_to_check);
										similarity.push(result);
									}
									//show the smallest number from the vector
									match similarity.iter().min() {
										Some(v) => println!("Closest similarity to {} is {}",
															&cache_entry_path.to_str().unwrap(), v),
										None => println!("No hashes in vector!"),
									}
								}
							}

                            if potential_file_path.is_dir() {
                                fs::remove_dir_all(&potential_file_path).unwrap();
                            }
                        }
                    }
                }
            } else {
                println!("Cannot read folder {:?}", folder_cache_path);
            }
        } else {
            println!("No cache folder found in profile {:?}", folder_cache_path)
        }
    }
}

fn extract_videoframes(input_file: PathBuf, output_file: PathBuf) {
    //extracts first frame of video into grayscale 32x32 raw
    let input = input_file.to_str().expect("Invalid input path");
    let output = output_file.to_str().expect("Invalid output path");

    FfmpegCommand::new()
        .args([
            "-i", input,
            "-vf", "scale=32:32",
            "-pix_fmt", "gray",
            //"-f", "rawvideo",
            "-f", "image2",
            output,
        ])
        .spawn()
        .expect("ffmpeg didn't even try :(")
        .wait()
        .expect("ffmpeg gave up :(");
}

fn hamming(a: u64, b: u64) -> u32 {
    (a ^ b).count_ones()
}

fn main() {
    //load dataset
    let dataset = load_dataset(); //<-- DONE
    
    //search video ids in browser
    
    browser_history_scan("librewolf", dataset.history_data); //<--DONE FOR LIBREWOLF/FIREFOX
    
    //scan browsers cache for cached files
    //for browser in vec!["librewolf"] {
	//	browser_cache_scan(browser, &dataset.video_data); //<--DONE FOR LIBREWOLF/FIREFOX
	//};
    
    println!("Done!");
}
