//No AI was used to write this program, I have alergy to ai slop. The only thing ai generated is
//the translation of pHash algorithm (which was ai generated by the author anyway)
//Also, i learned rust like 1 year ago, so this probably can be optimised
//
//28.05.2026 Added parsing data/video_data.txt into struct
//29.05.2026 Added parsing data/watch_page_data.txt, data/asset_data.txt, data/history_data.txt
//   into vectors, added searching through firefox's browsing history, added filetype checker,
//   added primitive browser cache scanner
//30.05.2026 Path are now proper PathBuf type not &str. Added FFmpeg extractor of frames from
//   videos. Added pHash generator from images. Added primitive comparator of hashes.
//31.05.2026 Replaced the good, well functioning pHash generator with ai generated translation of
//   pHash.cpp because they gave different results, improved frame extractor to use image2 instead of rawvideo,
//   improved comparator of hashes
//01.06.2026 Made "hash" of VideoData structure a vector.
//   Hashing works well, and fast

// TODO Generation of hashes and comparation should be
// in separate functions NOT in browser_cache_scan...
// TODO Make "0000000000000000" hash be a None.
// TODO Do something about the ffmpeg bottlneck maybe...
// TODO The most important functions (scanning) should return Result propperly instead of panicing
// TODO Chrome/Chromium stores cache in a weird format, process it

mod browser_paths;
mod dataset;
mod phash_ai_slop;

use dirs::home_dir;
use ffmpeg_sidecar::command::FfmpegCommand;
use ini::Ini;
use rusqlite::{params, Connection};
use serde_json::Value;
use std::path::{Path, PathBuf};
use std::sync::LazyLock;
use std::{env, fs};

//Constants and statics, mainly paths. LazyLock is a saviour <3
//MOVE ALL THOSE TO MATCH FUNCTIONS

static BASE_DIR: LazyLock<PathBuf> = LazyLock::new(|| {
    let path = PathBuf::from("./");
    if !path.is_dir() {
        panic!("Cannot read base dir!: {}", path.display());
    }

    path
});

fn detect_browsers(browser_paths: Vec<browser_paths::Browser>) -> Vec<browser_paths::Browser> {
    let mut detected_browser_paths: Vec<browser_paths::Browser> = Vec::new();
    let home_dir = home_dir().expect("Cannot read $HOME");
    for browser in browser_paths {
        if home_dir.join(browser.config_path).is_dir() {
            detected_browser_paths.push(browser);
        }
    }
    detected_browser_paths
}

fn get_profile_list(browser: &browser_paths::Browser) -> Vec<String> {
    let home_dir = home_dir().expect("Cannot read $HOME");

    let browser_config_profile_root = home_dir.join(browser.config_path);
    let profile_list_file_path = browser_config_profile_root.join(browser.profiles_file);
    let mut profile_list_vector: Vec<String> = Vec::new();

    let profiles_list_file_content =
        fs::read_to_string(profile_list_file_path).expect("Could not read file.");

    match browser.name {
        "firefox" | "librewolf" => {
            let profiles_list_ini = Ini::load_from_str(&profiles_list_file_content).unwrap();
            for (section, props) in profiles_list_ini.iter() {
                if let Some(section_name) = section {
                    if section_name.starts_with("Profile") {
                        match props.get("Path") {
                            Some(path) => profile_list_vector.push(path.to_owned()),
                            None => panic!("Profile section is missing Path value, skipping..."),
                        }
                    }
                }
            }
        }
        "chrome" | "chromium" => {
            let profile_list_json: Value =
                serde_json::from_str(&profiles_list_file_content).unwrap();

            if let Some(profiles) = profile_list_json["profile"]["info_cache"].as_object() {
                for (profile_dir, _) in profiles {
                    profile_list_vector.push(profile_dir.to_owned())
                }
            } else {
                panic!("No profiles found in Local State");
            }
        }
        _ => panic!("DAMN"),
    }

    profile_list_vector
}

fn browser_history_scan(browser: &browser_paths::Browser, search_vector: &Vec<String>) {
    println!("Scanning {}'s history...", &browser.name);
    let home_dir = home_dir().expect("No $HOME dir");

    let browser_config_profile_root = home_dir.join(browser.config_path);
    //get history file of a profile
    let profile_list_vector = get_profile_list(&browser);
    let profile_history = browser.history_file;

    for folder in profile_list_vector {
        let folder = PathBuf::from(folder);
        //firefox and its forks uses places.sqlite, chrome uses History which is (sqlite3)
        let history_file = browser_config_profile_root
            .join(folder.as_path())
            .join(&profile_history);
        if history_file.is_file() {
            println!("Scanning {}...", history_file.display());
            let conn = Connection::open(history_file).expect("Cannot open history database");

            let query = match browser.name {
                "firefox" | "librewolf" => "SELECT url, title FROM moz_places WHERE url LIKE ?1",
                "chrome" | "chromium" => "SELECT url, title FROM urls WHERE url LIKE ?1",
                _ => panic!("Browser not supported"),
            };

            let mut stmt = match conn.prepare(query) {
                Ok(response) => response,
                Err(error) => {
                    if let rusqlite::Error::SqliteFailure(err, _) = error {
                        match err.code {
                            rusqlite::ErrorCode::DatabaseBusy => {
                                panic!("The browser history database is locked, perhaps the browser is still running? Close it first.");
                            }
                            _ => panic!("Failed to prepare query due to an error: {:#?}", error),
                        }
                    } else {
                        panic!("Failed to prepare query due to an error: {:#?}", error);
                    }
                }
            };

            for search in search_vector {
                //build search querry
                let pattern = format!("%{}%", search);

                //prepare query that will search for stuff and execute it
                let mut rows = stmt.query(params![pattern]).expect("Query failed");

                // loop through rows
                while let Some(row) = rows.next().expect("Failed to fetch row") {
                    let url: Option<String> = row.get(0).unwrap_or_default();
                    let title: Option<String> = row.get(1).unwrap_or_default();
                    println!(
                        "Found: url: {}, title: {}",
                        url.unwrap_or_default(),
                        title.unwrap_or_default()
                    );
                }
            }
        } else {
            println!(
                "{} does not exists. No attempt to scan",
                history_file.display()
            )
        }
    }
}

// check file mime type
fn check_filetype(path: impl AsRef<Path>) -> Option<String> {
    let kind = infer::get_from_path(path).ok()??;
    Some(kind.mime_type().to_string())
}

fn browser_cache_scan(browser: &browser_paths::Browser, video_data: &Vec<dataset::VideoData>) {
    println!("Scanning {}'s cache...", browser.name);

    let home_dir = home_dir().expect("Cannot read $HOME");

    let profile_list_vector = get_profile_list(&browser);

    let browser_cache_profile_root = home_dir.join(browser.cache_path);
    let profile_cache = browser.cache_entries_path;

    for folder in profile_list_vector {
        let folder_cache_path = &browser_cache_profile_root.join(folder).join(&profile_cache);

        if folder_cache_path.is_dir() {
            println!("Scanning {:?}", folder_cache_path);
            if let Ok(cache_entries) = fs::read_dir(&folder_cache_path) {
                for cache_entry in cache_entries {
                    let cache_entry_path = cache_entry.unwrap().path();
                    //is it a file and a video file
                    if cache_entry_path.is_file() {
                        //initialize vector of similarity values
                        let mut similarity = Vec::new();
                        let mut similarity_pack = Vec::new();

                        let buf = fs::read(&cache_entry_path).unwrap();
                        if infer::is_video(&buf) {
                            //|| infer::is_image(&buf){
                            //println!("{:?}", cache_entry_path);
                            //extract frame and gen hash
                            let cache_entry_file_name = &cache_entry_path
                                .file_name()
                                .unwrap()
                                .to_string_lossy()
                                .into_owned();
                            println!("Checking {}", cache_entry_file_name);

                            //if the temporary dir is there remove it
                            //if not, create it, use it and then remove it
                            let potential_file_path = env::temp_dir().join(cache_entry_file_name);
                            if potential_file_path.is_dir() {
                                fs::remove_dir_all(&potential_file_path).unwrap();
                            }
                            fs::create_dir(&potential_file_path).unwrap();
                            let tmp_file = env::temp_dir()
                                .join(&cache_entry_file_name)
                                .join("frame_%03d.raw");

                            extract_videoframes(
                                PathBuf::from(&cache_entry_path),
                                PathBuf::from(&tmp_file),
                            );

                            for video_data_entry in video_data {
                                println!("{:?}", video_data_entry.title);
                                for file in fs::read_dir(&potential_file_path).unwrap() {
                                    let path = file.unwrap().path();
                                    let filepath = path.to_str().unwrap();
                                    let hash_to_check = phash_ai_slop::generate_phash(filepath);
                                    for &video_entry_hash in &video_data_entry.hash {
                                        let result = hamming(video_entry_hash, hash_to_check);
                                        similarity.push(result);
                                    }
                                    match similarity.iter().min().cloned() {
                                        //Some(v) => println!(
                                        //	"Closest similarity to {} is {}",
                                        //	&cache_entry_path.to_str().unwrap(),
                                        //	v
                                        //),
                                        Some(v) => similarity_pack.push(v),
                                        None => println!("No hashes in vector!"),
                                    }
                                }
                                println!("Similarity: {:?}", similarity_pack.iter().min().unwrap());
                            }

                            //remove temp directories with raw files afterwards
                            if potential_file_path.is_dir() {
                                fs::remove_dir_all(&potential_file_path).unwrap();
                            }
                        }
                    }
                }
            } else {
                println!("Cannot read folder {:?}", folder_cache_path);
            }
        } else {
            println!("No cache folder found in profile {:?}", folder_cache_path)
        }
    }
}

fn extract_videoframes(input_file: PathBuf, output_file: PathBuf) {
    //extracts first frame of video into grayscale 32x32 raw
    let input = input_file.to_str().expect("Invalid input path");
    let output = output_file.to_str().expect("Invalid output path");

    FfmpegCommand::new()
        .args([
            "-i",
            input,
            "-vf",
            "scale=32:32",
            "-pix_fmt",
            "gray",
            //"-f", "rawvideo",
            "-f",
            "image2",
            output,
        ])
        .spawn()
        .expect("ffmpeg didn't even try :(")
        .wait()
        .expect("ffmpeg gave up :(");
}

///Calculates the difference between two given hashes
fn hamming(a: u64, b: u64) -> u32 {
    (a ^ b).count_ones()
}

fn main() {
    //load browser paths
    let browser_paths = browser_paths::SUPPORTED_BROWSERS.to_vec();
    //detect browsers installed on the pc
    let detected_browsers = detect_browsers(browser_paths);
    println!("{:#?}", &detected_browsers);

    //load dataset
    let dataset = dataset::load_dataset(BASE_DIR.join("data")); //<-- DONE

    for browser in &detected_browsers {
        //search video ids in browser history
        browser_history_scan(&browser, &dataset.history_data); //<--DONE FOR LIBREWOLF/FIREFOX/CHROME/CHROMIUM
    }
    for browser in &detected_browsers {
        browser_cache_scan(&browser, &dataset.video_data); //<--DONE FOR LIBREWOLF/FIREFOX/CHROME/CHROMIUM
    }

    println!("Done!");
}
